<a href="https://colab.research.google.com/github/EzinneUfondu/python_new/blob/main/ML_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load your Dataset

In [8]:
import pandas as pd

df=pd.read_csv('/content/Data_Feb_2026.csv')

print(df.shape)
print(df.head())
print(df.dtypes)

(1375, 5)
        X1      X2      X3       X4  Label
0  3.62160  8.6661 -2.8073 -0.44699    0.0
1  4.54590  8.1674 -2.4586 -1.46210    0.0
2  3.86600 -2.6383  1.9242  0.10645    0.0
3  3.45660  9.5228 -4.0112 -3.59440    0.0
4  0.32924 -4.4552  4.5718 -0.98880    0.0
X1       float64
X2       float64
X3       float64
X4       float64
Label    float64
dtype: object

#### Check for Missing Values

In [9]:
df.isnull().sum()

X1       0
X2       0
X3       0
X4       0
Label    1
dtype: int64

##### Check for Duplicate Rows

In [13]:
df.duplicated().sum()

np.int64(25)

#### Descriptive Statistics

In [17]:
df.describe()

                X1           X2           X3           X4        Label
count  1375.000000  1375.000000  1375.000000  1375.000000  1374.000000
mean      0.386657     2.014202     1.359162    -1.250522     0.443959
std       3.418977     6.676094     4.527056     2.987968     0.497030
min     -70.000000   -13.773100   -50.000000   -80.000000     0.000000
25%      -1.774700    -1.697850    -1.630450    -2.428000     0.000000
50%       0.496650     2.325900     0.616630    -0.586650     0.000000
75%       2.822050     6.819300     3.181600     0.394810     1.000000
max       6.824800   120.000000    17.927400     2.449500     1.000000

#### Label Column Integrity Check

In [16]:
print(df['Label'].unique())
print(df['Label'].value_counts())

[ 0. nan  1.]
Label
0.0    764
1.0    610
Name: count, dtype: int64

In [18]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 25